name: Autosync

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"

jobs:
  sync:
    name: Synchronize production database
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
        
    - name: Build
      run: dotnet publish PRUNStatsSynchronizer -c Release -o Release

    - name: Run sync
      run: ./Release/PRUNStatsSynchronizer.exe -- ${{ secrets.DB_CONNSTRING }}
        
