name: Publish

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore PRUNStatsApp\PRUNStatsApp.csproj
      
    - name: Publish
      run: dotnet publish PRUNStatsApp -c Release -o Release --no-restore

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: new-build
        path: Release
        if-no-files-found: error
        
  deploy:
    needs: build
    name: Deploy
    runs-on: windows-latest

    steps:
    - name: Download artifact for deployment job
      uses: actions/download-artifact@v4
      with:
        name: new-build
        path: publish

    - name: SmarterASP.NET Web Deploy
      uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
      with:
        website-name: ${{ secrets.WEBSITE_NAME }}
        server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
        server-username: ${{ secrets.SERVER_USERNAME }}
        server-password: ${{ secrets.SERVER_PASSWORD }}
        
